server:
  port: 0
  
spring:
  application:
    name: wm-bootadmin-server

eureka: 
  client:
    service-url:
      defaultZone: http://eureka.didispace.com/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.int(4000,10000)}}
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 20
    health-check-url-path: /actuator/health
