spring: 
  mail:
    default-encoding: UTF-8
    host: smtp-mail.outlook.com
    password: weiming123
    port: 25
    protocol: smtp
    test-connection: false
    username: wm.root@outlook.com
    properties: 
      mail: 
        smtp: 
          auth: true
          starttls: 
            enable: true
          quitwait: false
        transport: 
          protocol: smtps
  rabbitmq: 
    host: www.2133.online
    username: admin
    password: 123456
    port: 5672
  application:
    name: wm-cpt-emailsend
    
server: 
  port: 0

#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka
#  instance:
#    prefer-ip-address: true
#    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.int(4000,10000)}}
#    lease-renewal-interval-in-seconds: 10
#    lease-expiration-duration-in-seconds: 20