server:
  port: 8000
  
spring:
  application:
    name: wm-demo-bootadmin-server
    
eureka:   
  instance:
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://eureka.didispace.com/eureka/

management:
  endpoints:
    web:
      exposure:
        include:
        - "*"
  endpoint:
    health:
      show-details: ALWAYS