server:
  port: 0
spring:
  application:
    name: auth-server
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.int(4000,10000)}}
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 20